runtime: python
vm: true
service: podtube
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  youtube_developer_key: 'INPUT HERE YOUR YOUTUBE DEVELOPER KEY'
